# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12f2c45351b3c4f843568044db01a0731fc82f1b261fb252c968d9b39df6f5941c728428d9894f6930f1a5b1fe8d1d6ab353f576ff76713f577928a4e5e7e26

test:
  secret_key_base: 3b2953507071e5fb8309443b5251e2072b9eb7c51e9227ec42ca4dff3b8ee4b090f244c23e8078d4392297cf73f0dbbbdd3d84dcfbf32fc5e39efca35befc0ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
